### ISSUE TITLE
[Meta] MQTT 5 support development

### ISSUE THREAD

**Issue by andsel** [moquette-io/moquette#695]
This issue is a meta issue to track all the changes that needs to be done in order to support MQTT5 version of the protocol.
 
- [x] Update the Netty to the latest to have full MQTT 5 version protocol support #696
- [ ] Connection management
  - [x] accepts a v5 connection message
    - [x]  avoid to resend `PUBLISH` and `PUBREL` with a [timed handler](https://github.com/moquette-io/moquette/blob/3b2b85f924f689ca30a26093604ed6083faf37eb/broker/src/main/java/io/moquette/broker/InflightResender.java#L32), spec [[MQTT-4.4.0-1](https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901238)]
"When a Client reconnects with Clean Start set to 0 and a session is present, both the Client and Server MUST resend any unacknowledged `PUBLISH` packets (where QoS > 0) and `PUBREL` packets using their original Packet Identifiers. This is the only circumstance where a Client or Server is REQUIRED to resend messages. Clients and Servers MUST NOT resend messages at any other time." #697
    - [x]  Reply to a connect with the capabilites offered (Retain Available, Maximum QoS, Server Keep Alive) in [ConnACK properties](https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901080). #709
    - [x] Reply with proper `CONNACK` reason strings and reason codes. #713
    - [x]  Switch from `cleanSession` to `cleanStart` flag and `SessionExpiryInterval` property #753 and #764
  - [x] #767
 The Server delays publishing the Client’s Will Message until the Will Delay Interval has passed 
or the Session ends, whichever happens first. If a new Network Connection to this Session
 is made before the Will Delay Interval has passed, the Server MUST NOT send the Will Message [MQTT-3.1.3-9].
  - [x] #789
  - [ ] **Assigned ClientID:** In cases where the ClientID is assigned by the Server, return the assigned ClientID. This also lifts the restriction that Server assigned ClientIDs can only be used with Clean Session=1 connections.
  - [ ] **Server reference:** Allow the Server to specify an alternate Server to use on CONNACK or DISCONNECT. This can be used as a redirect or to do provisioning.
  - [ ] **Maximum Packet Size:** Allow the Client and Server to independently specify the maximum packet size they support. It is an error for the session partner to send a larger packet.

- [x]  Subscription
  - [x] **Shared Subscriptions:** Add shared subscription support allowing for load balanced consumers of a subscription.  #791
  - [x] **Subscription ID:** Allow a numeric subscription identifier to be specified on a SUBSCRIBE, and returned on the message when it is delivered. This allows the Client to determine which subscription or subscriptions caused the message to be delivered. #801 
  - [x] **Subscription options:** Provide subscription options primarily defined to allow for message bridge applications. These include an option to not send messages originating on this Client (noLocal), and options for handling retained messages on subscribe. #808
  
- [ ] Various aspects
  - [x] **Message expiry:** Allow an expiry interval to be set when a message is published. #818 
  - [x] #825
  - [x] #829
  - [x] #847
  - [x] #876
  - [x] #880
  - [ ] **Enhanced authentication:** Provide a mechanism to enable challenge/response style authentication including mutual authentication. This allows SASL style authentication to be used if supported by both Client and Server, and includes the ability for a Client to re-authenticate within a connection.
  - [x] #859

----

## Other secondary features
- [ ] provide a way to define (in config file maybe) the `User properties` to return with `CONNACK`.
- [ ] provide a  way to define `Server reference` in `CONNACK` and `DISCONNECT`.

    
----
## Useful refs
- **Development branch**: https://github.com/moquette-io/moquette/tree/main
- HiveMQ blog series: https://www.hivemq.com/tags/mqtt-5-essentials/
- Oasis specification: https://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.html
- Previous work: https://github.com/moquette-io/moquette/pull/558

**Comment by hylkevds** [comment]
Some more features of MQTT5:

- [ ] **Message expiry:** Allow an expiry interval to be set when a message is published.
- [ ] **Payload format and content type:** Allow the payload format (binary, text) and a MIME style content type to be specified when a message is published. These are forwarded on to the receiver of the message.
- [ ] **Request / Response:** Formalize the request/response pattern within MQTT and provide the Response Topic and Correlation Data properties to allow response messages to be routed back to the publisher of a request. Also, add the ability for the Client to get configuration information from the Server about how to construct the response topics.
This ties into security, since each client should get a (configurable) part of the topic tree for itself that other clients are not allowed to subscribe to
- [ ] **Shared Subscriptions:** Add shared subscription support allowing for load balanced consumers of a subscription
- [ ] **Subscription ID:** Allow a numeric subscription identifier to be specified on a SUBSCRIBE, and returned on the message when it is delivered. This allows the Client to determine which subscription or subscriptions caused the message to be delivered.
- [ ] **Flow control:** Allow the Client and Server to independently specify the number of outstanding reliable messages (QoS>0) they allow. The sender pauses sending such messages to stay below this quota. This is used to limit the rate of reliable messages, and to limit how many are in flight at one time.
- [ ] **User properties:** Add User Properties to most packets. User properties on PUBLISH are included with the message and are defined by the Client applications. The user properties on PUBLISH and Will Properties are forwarded by the Server to the receiver of the message. User properties on the CONNECT, SUBSCRIBE, and UNSUBSCRIBE packets are defined by the Server implementation. The user properties on CONNACK PUBACK, PUBREC, PUBREL, PUBCOMP, SUBACK, UNSUBACK and AUTH packets are defined by the sender, and are unique to the sender implementation. The meaning of user properties is not defined by MQTT.
- [ ] **Maximum Packet Size:** Allow the Client and Server to independently specify the maximum packet size they support. It is an error for the session partner to send a larger packet.
- [ ] **Optional Server feature availability:** Define a set of features which the Server does not allow and provide a mechanism for the Server to specify this to the Client. The features which can be specified in this way are: Maximum QoS, Retain Available, Wildcard Subscription Available, Subscription Identifier Available, and Shared Subscription Available. It is an error for the Client to use features that the Server has declared are not available.
- [ ] **Enhanced authentication:** Provide a mechanism to enable challenge/response style authentication including mutual authentication. This allows SASL style authentication to be used if supported by both Client and Server, and includes the ability for a Client to re-authenticate within a connection.
- [ ] **Subscription options:** Provide subscription options primarily defined to allow for message bridge applications. These include an option to not send messages originating on this Client (noLocal), and options for handling retained messages on subscribe.
- [ ] **Will delay:** Add the ability to specify a delay between the end of the connection and sending the will message. This is designed so that if a connection to the session is re-established then the will message is not sent. This allows for brief interruptions of the connection without notification to others.
- [ ] **Server Keep Alive:** Allow the Server to specify the value it wishes the Client to use as a keep alive. This allows the Server to set a maximum allowed keepalive and still have the Client honor it.
- [ ] **Assigned ClientID:** In cases where the ClientID is assigned by the Server, return the assigned ClientID. This also lifts the restriction that Server assigned ClientIDs can only be used with Clean Session=1 connections.
- [ ] **Server reference:** Allow the Server to specify an alternate Server to use on CONNACK or DISCONNECT. This can be used as a redirect or to do provisioning.

**Comment by andsel** [comment]
Thank's @hylkevds  for crafting the list
